#!/usr/bin/env python3
"""
Create a gmsh .geo file from a tagged contour.

Expected input format (ASCII):
  x y tag

Each segment takes the tag of its first (start) point. For a closed
rectangle matching ice_slab / Calving3D BC numbering, use:

  x=0,y=0,tag=4       # start of calving front
  x=W,y=0,tag=1       # start of right sidewall
  x=W,y=L,tag=2       # start of backwall / inflow
  x=0,y=L,tag=3       # start of left sidewall
  x=0,y=0,tag=4       # close contour
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import numpy as np


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert tagged contour to .geo")
    parser.add_argument("-i", "--input", default="Block_Contour_tagged.dat")
    parser.add_argument("-o", "--output", default="PlanMeshDEM.geo")
    parser.add_argument("-r", "--resolution", type=float, default=100.0)
    args = parser.parse_args()

    data = np.loadtxt(args.input)
    if data.ndim != 2 or data.shape[1] < 3:
        raise ValueError("Input must have 3 columns: x y tag")

    x = data[:, 0]
    y = data[:, 1]
    tags = data[:, 2].astype(int)

    # Ensure closed contour.
    if not (np.isclose(x[0], x[-1]) and np.isclose(y[0], y[-1])):
        x = np.append(x, x[0])
        y = np.append(y, y[0])
        tags = np.append(tags, tags[0])

    npts = len(x) - 1
    segs_by_tag: dict[int, list[int]] = defaultdict(list)

    out = []
    out.append("// Generated by Contour2geo_tagged.py")
    out.append("Mesh.Algorithm = 5;")
    out.append(f"lc = {args.resolution};")
    out.append("Mesh.CharacteristicLengthFromCurvature = 0;")
    out.append("Mesh.CharacteristicLengthFromPoints = 1;")
    out.append("Mesh.CharacteristicLengthExtendFromBoundary = 0;")
    out.append("Field[1] = MathEval;")
    out.append('Field[1].F = Sprintf("%g", lc);')
    out.append("Background Field = 1;")

    for i in range(npts):
        out.append(f"Point({i+1}) = {{{x[i]}, {y[i]}, 0.0, lc}};")

    for i in range(npts):
        i0 = i + 1
        i1 = i + 2 if i + 2 <= npts else 1
        lid = i + 1
        out.append(f"Line({lid}) = {{{i0},{i1}}};")
        segs_by_tag[int(tags[i])].append(lid)

    out.append(f"Curve Loop(1) = {{1:{npts}}};")
    out.append("Plane Surface(1) = {1};")
    out.append("Physical Surface(1) = {1};")

    # Boundary tags are preserved directly as Physical Curve IDs.
    for tag in sorted(segs_by_tag):
        lines = ",".join(str(l) for l in segs_by_tag[tag])
        out.append(f"Physical Curve({tag}) = {{{lines}}};")

    Path(args.output).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {args.output} with boundary tags: {sorted(segs_by_tag)}")


if __name__ == "__main__":
    main()
